### ISSUE TITLE
Calling pyNeuroML functions such as NML2ChannelAnalysis.main(), etc from a python script

### ISSUE THREAD

**Issue by VahidGh** [NeuroML/pyNeuroML#10]
I'm not sure if it is possible to call the main() function of the `NML2ChannelAnalysis.py` from a python script, and passing a neuroml2 file for analysis (I couldn't do this).
If it was possible, would be very helpful, as one of the main purposes of the pyNeuroML is to ease using NeuroML+Python.

**Comment by rgerkin** [comment]
@VahidGh [My revisions](https://github.com/NeuroML/pyNeuroML/commit/85d26129560b55f092c00e1e171387e23708e62d) to that `NML2ChannelAnalysis.py` should have made this possible.  For example, `process_channel_file`, `make_lems_file`, etc.  Basically these are taking .nml files and doing stuff with them, e.g. creating objects for further use.  I did this because I, too, wanted to interact with the useful `NML2ChannelAnalysis.py` written by @pgleeson, but from within a python script.  What is your specific use case?

**Comment by VahidGh** [comment]
@rgerkin, Yeah, this Python script was really helpful to me. 
The specific case I'm talking about is to be able to run: `NML2ChannelAnalysis.main(foo.channel.nml)` instead of `pynml-channelanalysis foo.channel.nml`.

**Comment by rgerkin** [comment]
@VahidGh My revisions allow you to do this:  

```
NML2ChannelAnalysis.run(channel_files=['/path/to/foo.channel.nml'],nogui=True)
```

And add other flags as needed.

**Comment by VahidGh** [comment]
@rgerkin, Worked for me, thanks.
