### ISSUE TITLE
Provide cleaner error messages

### ISSUE THREAD

**Issue by jonrkarr** [NeuroML/pyNeuroML#125]
The error messages from pyNeuroML are hard to read because they're wrapped by Java. It would be helpful to strip that formatting out to provide more readable message.

**Describe the solution you'd like**
Cleanup the formatting of the messages

**Describe alternatives you've considered**
Parsing the error messages myself

**Comment by sanjayankur31** [comment]
Since pynml calls jNeuroML under the hood, the messages include the java prefixes etc. I think some amount of parsing will be required here---we can't remove all the wrappers because they are useful for folks using the command line tools.

I'll close this for the moment, but please feel free to re-open it if you have any specific suggestions on how we can make the error messages more parseable.
