### ISSUE TITLE
As a user, I would like to add headers to the output files I generate so I can easily see what was recorded in each item at a later date

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#214]
We don't include headers in output files at the moment. I'll be good to include these. Large files with lots of columns are otherwise hard to understand at a later date.

**Comment by sanjayankur31** [comment]
@pgleeson : I expect this will also require tweaks to the writers, but opened it here for initial tracking

**Comment by pgleeson** [comment]
There's plenty of options for headers/trace info in the Sonata simulation data save format, which is also much more compact. Probably best to spend effort on adding support for that rather than extending the intentionally simple text/dat format output... 
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007696

**Comment by sanjayankur31** [comment]
Yeh, probably a better way to go. We'll also need to update/tweak a lot of our plotting etc. utils to work with sonata then---should be a case of adding wrappers to read sonata data files using the sonata file and then using our current utils.
