### ISSUE TITLE
Functions to generate LEMS files from NeuroML files + args

### ISSUE THREAD

**Issue by rgerkin** [NeuroML/pyNeuroML#4]
As far as I can tell, the ability to generate LEMS files is buried within `main()` in analysis scripts like `pyneuroml/analysis/NML2ChannelAnalysis.py`.  I would like to break this out into its own functions, and I am wondering how general these can be.  For example, channel files might require different treatment from neuron files.  

I had written something like this:  
```
def make_lems(nml_file_path,tool,**kwargs):
    """Creates a LEMS file from a NeuroML file with parameters."""
    print(tool.__name__)
    assert tool.__name__.split('.')[-1] in \
        ['NML2ChannelAnalyse', 'NML2ChannelAnalysis'], "Not a supported tool"
    lems_file_path = None
    args = argparse.Namespace()
    args.channelFiles = [nml_file_path]
    #args.target_file = nml_file_path
    args.nogui = True
    for key,value in kwargs.items():
        setattr(args,key,value)
    if hasattr(tool,'DEFAULTS'):
        for key,value in tool.DEFAULTS.items():
            if not hasattr(args,key):
                setattr(args,key,value)
    lems_file_path = tool.main(args=args)
    lems_file_path = os.path.join(os.getcwd(),lems_file_path)
    return lems_file_path
```

which takes a tool (a script, e.g. `NML2ChannelAnalysis.py`, or the old `NML2ChannelAnalyse.py`) as an argument, and then invokes the tool's `main()` with appropriate arguments to get a lems file.  I think this could be a reasonably general strategy that leaves the specifics to those analysis scripts, but provides a frontend to always get a LEMS file out, which can then be sent to `pynml.run_jneuroml`.  

Each script would then just need its defaults in a global and an optional `args` argument added to `main()`

**Comment by pgleeson** [comment]
Have you seen https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/lems/LEMSSimulation.py? This makes it possible to make a complete LEMS files from scratch through Python. See main() there for usage. 

Templates were used here as the structure of the generated analysis script was known in advance and wouldn't change much. 

It would certainly be possible to extract the core functionality from NML2ChannelAnalysis.py to make a more readliy callable method, but a more generic lems generator is probably better handled through LEMSSimulation.py

**Comment by rgerkin** [comment]
Great!  How do you handle all the parameters (temperature, Ca concentration, etc.)?  I didn't see any option for those arguments.  Also, given that this exists, should NML2ChannelAnalysis be updated to use it?

**Comment by pgleeson** [comment]
Parameters like temperature, Ca concentration etc. are part of the NeuroML definition of the model, and would be set by loading in the original nml, changing values with libNeuroML and rewriting the XML file. You could make a helper class/method to read/write the nml, just accepting the values you want to change as parameters. 

NML2ChannelAnalysis uses a template mainly because LEMSSimulation.py didn't exist at the time, but will probably stay as a template, because it writes a single file that mixes a new LEMS Comp type definition, some NeuroML types (e.g. network) & a LEMS Simulation element into one file. Having a template made it easy to edit everything in one place and produce a working standalone LEMS file. The file could be built up from scratch (now) using a combination of pylems, pyneuroml & libNeuroML, but having everything in one place makes it easier to see the big picture.

See here for an example which uses pylems, pyneuroml & libNeuroML to build a set of files for running a simulation using custom lems elements & nml2: https://github.com/epiasini/neuroml_use_case/blob/master/tested_script.py

**Comment by pgleeson** [comment]
@rgerkin closing this as the recommended method for generating a new LEMS file is generate_lems_file_for_neuroml() in https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/lems/__init__.py.

NML2ChannelAnalysis probably won't be updated to use this as it depends highly on the template file.

If a generic NML2 file needs to be loaded changed and a LEMS file generated, then it's best to use libNeuroML to load the NML2, and use generate_lems_file_for_neuroml(), or LEMSSimulation directly, to create the LEMS, as is done in [generate_current_vs_frequency_curve()](https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/analysis/__init__.py)
