### ISSUE TITLE
Check if users are passing the correct file type for various pynml commands

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#406]
For example, if a user tries to "run" a NeuroML file, they get a somewhat cryptic error from jneuroml. We could check if the files are the correct ones for various commands and inform the user before jneuroml gets involved.

**Comment by subhacom** [comment]
I realized that this is rather a documentation issue. The pyneuoml readme file could describe how to run a model in more detail. The pynml help message needs some work. To start with, the first line it prints is:

`usage: pynml [-h|--help] [<shared options>] <one of the mutually-exclusive options>`

Traditionally, a program that takes an input file as an argument, would say something like 

`usage: pynml [-h|--help] [<shared options>] <one of the mutually-exclusive options> filename`

The help message lists `-run` as a sub-option for the third-party simulators like neuron, but does not tell that by default it would run the model on LEMS simulator. In some cases it mentions `<LEMS file>` as the argument as part of the mutually exclusive options, but at other times not. So probably the input file argument is not mentioned in the one-liner help, but then it should be mentioned consistently in the option specification.

The help message also mentions NeuroML2 only for `-svg`, `-png`, and `-validate` options, but not how to get a LEMS file out of a NeuroML2 file. Somebody trying to work with NeuroML would naturally try to run a NeuroML2 file at first instead of a LEMS file.

**Comment by sanjayankur31** [comment]
> The help message also mentions NeuroML2 only for `-svg`, `-png`, and `-validate` options, but not how to get a LEMS file out of a NeuroML2 file. Somebody trying to work with NeuroML would naturally try to run a NeuroML2 file at first instead of a LEMS file.

So, a NeuroML file is already valid LEMS. It's just that it does not have the LEMS Simulation description/object that is required to simulate it---it is not runnable. A NeuroML file could just describe a cell, for example. Users do have to be able to create a simulation out of the model. 

NeuroML by design separates model description from simulation description. Our getting started examples talk about this, but we can make it clearer. 

https://docs.neuroml.org/Userdocs/SingleNeuronExample.html#simulating-the-model

**Comment by pgleeson** [comment]
I feel like I'm going crazy, but I was pretty sure this had been implemented already, and that there was a helper function called at each simulate/export option X which looked at the input file and said things exactly like "you have asked to run/simulate in format X, but this command requires a LEMS file (or NeuroML file)" if the input file format was wrong... Any recollection of that @sanjayankur31? Notsure if it was in jnml or pynml...

**Comment by sanjayankur31** [comment]
Im sure we have these checks but perhaps theyre not applied to all
operations? Ill check the code and update it. Should be a simple enough fix.
-- 
Thanks,

Ankur

(Sent from mobile device)

**Comment by sanjayankur31** [comment]
@pgleeson : our check for lems files is weak:

https://github.com/NeuroML/pyNeuroML/blob/development/pyneuroml/io.py#L255

we don't check that it's a LEMS file. We check if it's a NML file and throw a warning.

I'll correct this and then see if it breaks anything. I don't think there are any commands that can take both LEMS/NML files, but if they do, I can make the check intelligent enough to handle multiple filetypes.
