### ISSUE TITLE
pynml-povray does not create correct camera location

### ISSUE THREAD

**Issue by orena1** [NeuroML/pyNeuroML#55]
Hello,
See following example:  
[cell3_new2_fixz_3.nml.zip](https://github.com/NeuroML/pyNeuroML/files/2031292/cell3_new2_fixz_3.nml.zip)

```
pynml-povray cell3_new2_fixz_3.nml
povray cell3_new2_fixz_3.nml.pov
```

Thanks.

**Comment by pgleeson** [comment]
@orena1, the issue seems to be the xyz locations of the segments are shifted from (0,0,0) in the cell and so the default view (which I believe includes the origin) is quite large and you have to use the options for pynml-povray to view the cell correctly. One quick way to look at this or any other nml file which is usually easier to focus on the real cells is:

    jnml cell3_new2_fixz_3.nml -png   # Note pynml works for this too
    or
    jnml cell3_new2_fixz_3.nml -svg  

and you can see it's off away from the origin:

![cell3_new2_fixz_3](https://user-images.githubusercontent.com/1556687/40436346-b317b9ba-5eaa-11e8-8e58-3dfa9dd3e8d4.png)

Some options to see this with pynml-povray are:

      pynml-povray -scalez 15   cell3_new2_fixz_3.nml
      pynml-povray   cell3_new2_fixz_3.nml -viewx -.8 -viewy .3

or for a movie:

     pynml-povray  cell3_new2_fixz_3.nml -viewx -1 -viewy .5 -movie
     povray cell3_new2_fixz_3.nml_movie.ini

However moving the cell to the origin (set `<instance><location x=...>...`) will improve the usability of pynml-povray

**Comment by orena1** [comment]
Thanks. I forgot to write h.define_shape()
It is working now.

**Comment by pgleeson** [comment]
Good to hear.

**Comment by pgleeson** [comment]
BTW most if not all of the command line options for jnml work for pynml also...
