### ISSUE TITLE
Using bundled jneuroml jar may cause some confusion if a user has also installed jneuroml separately

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/pyNeuroML#65]
Given that pyneuroml bundles the jar, a user that has installed jneuroml separately may end up a little confused about what version of jneuroml is being used. (this can then translate into more confusion when it comes to debugging things)

Can we do something to make pyneuroml only fallback to the bundled jar if it cannot find a jneuroml installation perhaps? Otherwise, these two are very strongly coupled, and there's no real advantage of having two copies of the jneuroml jar installed for the user.

**Comment by pgleeson** [comment]
The functionality of the python side is completely tied to the jar, so it needs to be sure it has the correct jar present. If someone has the native jnml jar installed, they probably know what they're doing and will know when they're using that rather than python, but in the other case a pynml only user probably doesn't care about the java side and it should be kep bundled in the background. 

Both are released ast the same time usually anyway, so not too many problems should arise...

**Comment by sanjayankur31** [comment]
I don't think we should assume that users know what they're doing :laughing: . Because `pynml` spits out commands showing `jnml` running under the hood, people may try to use `jnml`, especially since it is the reference implementaion for neuroml.

I can think of two ways to prevent any mixups:

- we make sure that jnml releases and pynml releases that bundle the jnml jar are strongly synched
- we relegate the bits of the pynml output that explicitly show jnml calls to a `-debug` flag, and not make them visible to the user normally
